version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: atom-languageclient
    versions:
    - 1.0.6
    - 1.0.7
    - 1.1.1
    - 1.2.0
    - 1.2.2
    - 1.4.0
    - 1.6.0
    - 1.7.0
    - 1.8.2
  - dependency-name: "@types/atom"
    versions:
    - 1.40.7
    - 1.40.9
  - dependency-name: atom-package-deps
    versions:
    - 7.1.0
    - 7.2.0
    - 7.2.1
    - 7.2.2
  - dependency-name: lodash
    versions:
    - 4.17.20
